spring:
  profiles:
    active: local #basic configuration select
    
#local environment
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
    